FROM oven/bun:alpine AS build
RUN apk add --no-cache git

# Setting working directory
WORKDIR /opt/meilisearch-ui

# Copying source files
COPY . .

# Installing dependencies
RUN bun install

RUN bun pm untrusted

# Build the app
RUN bun run build

# -------
FROM nginx

COPY --from=build /opt/meilisearch-ui/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 24900
